services:
  db-paciente-registro:
    build:
      context: ./src/main/resources/db/.
      dockerfile: Dockerfile-bd
    container_name: postgres-timescale-paciente-registro
    environment:
      - POSTGRES_USER=${DB_USER_PACIENTE_REGISTRO}
      - POSTGRES_PASSWORD=${DB_PASSWORD_PACIENTE_REGISTRO}
      - POSTGRES_DB=${DB_NAME_PACIENTE_REGISTRO}
    ports:
      - "${DB_PORT_PACIENTE_REGISTRO}:5432"
    # A extensão precisa ser pré-carregada na inicialização do serviço
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]
    volumes:
      - pg_paciente_registro_data:/var/lib/postgresql/data
  db-acompanhamento:
    image: postgres:16-alpine
    container_name: postgres-acompanhamento
    environment:
      - POSTGRES_USER=${DB_USER_ACOMPANHAMENTO}
      - POSTGRES_PASSWORD=${DB_PASSWORD_ACOMPANHAMENTO}
      - POSTGRES_DB=${DB_NAME_ACOMPANHAMENTO}
    ports:
      - "${DB_PORT_ACOMPANHAMENTO}:5432"
    volumes:
      - pg_acompanhamento_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta de comunicação das APIs (backend)
      - "15672:15672" # Porta da interface visual para os jurados
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

volumes:
  pg_paciente_registro_data:
  pg_acompanhamento_data: